
[character]
error_symbol = "[âœ–](bold red)"

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[[battery.display]]
threshold = 15
style = "bold red"

[directory]
truncation_length = 5
#format = "[$path]($style)[$lock_symbol]($lock_style) "

[docker_context]
disabled = false
only_with_files = true

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
#untracked = "ğŸ›¤ï¸  Ã—${count}"
#stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
#staged = "ğŸ—ƒï¸  Ã—${count}"
#renamed = "ğŸ“› Ã—${count}"
#deleted = "ğŸ—‘ï¸  Ã—${count}"
#style = "bright-white"
#format = "$all_status$ahead_behind"

[kubernetes]
format = 'on [â›µ $context](dimmed green) '
#format = 'on [â›µ $context \($namespace\)](dimmed green) '
disabled = false

